name: Test All Scores

on: workflow_dispatch

jobs:

  test:

    strategy:
      matrix:

        runner_image:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        compiler:
          - gcc
          #FIXME: - clang

    runs-on: ${{ matrix.runner_image }}

    env:
      CC: ${{ matrix.compiler }}

    steps:

    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup-python
      uses: actions/setup-python@v5

    - name: build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: builddir_test
        setup-options: -Dbuildtype=release -Dtest_all_scores=enabled
        meson-version: 1.4.0
        ninja-version: 1.11.1

    - name: test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: builddir_test
        meson-version: 1.4.0
        ninja-version: 1.11.1
